# debug level setting
# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# WARN = WARNING
# INFO = 20
# DEBUG = 10
# NOTSET = 0
LogLevel: 10

GoogleRSS:
# google rss url
  url: 'https://news.google.com/rss?hl=zh-TW&gl=TW&ceid=TW:zh-Hant'

OUTPUT:
# the question 1 output save path
  q1_path: './output/q1/'

# the question 2 output save path
  q2_path: './output/q2/'
