# debug level setting
# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# WARN = WARNING
# INFO = 20
# DEBUG = 10
# NOTSET = 0
LogLevel: 10

GoogleRSS:
  url: 'https://news.google.com/rss?hl=zh-TW&gl=TW&ceid=TW:zh-Hant'

OUTPUT:
  q1_path: './output/q1/'
  q1_rss: 'news.rss'
  q1_description: 'description.txt'
  q1_output: 'output.txt:'
  q2_path: './output/q2/'
